# fly.toml app configuration file generated for icp-off-chain-agent-test on 2024-04-12T17:29:18+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'icp-off-chain-agent'
primary_region = 'cdg'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[env]
PORT = '8080'

#[http_service]
#internal_port = 8080
#force_https = true
#auto_stop_machines = true
#auto_start_machines = true
#min_machines_running = 1
#processes = ['app']

#[[http_service.checks]]
#path = '/healthz'


#[[services.ports]]
#port = 80
#handlers = ['http']

[[services]]
internal_port = 50051
protocol = "tcp"
processes = ["app"]

[[services.ports]]
handlers = ["tls"]
port = 443

[services.ports.tls_options]
alpn = ["h2"]

[services.concurrency]
hard_limit = 25
soft_limit = 20

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 2
