name: Build and Check linting

on:
  workflow_call:
    inputs:
      publish-artifact:
        default: false
        required: false
        type: boolean
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Cache and Install prereqs
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: protobuf-compiler
          version: 1.0 # cache version, for manual invalidation

      # - name: Setup Go
      #   uses: actions/setup-go@v5
      #   with:
      #     go-version: "stable"

      - name: Rust Setup
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "stable"
          targets: "x86_64-unknown-linux-gnu"

      - name: Build setup
        run: |
          rustup target add x86_64-unknown-linux-gnu

      - name: Use rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-gnu
      # - name: Run tests
      #   run: cargo test --verbose
      - run: touch .empty
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        if: ${{ inputs.publish-artifact }}
        with:
          name: build-glibc
          path: |
            target/x86_64-unknown-linux-gnu/release/icp-off-chain-agent
            .empty
